version: "3.9"
services:
  test_db:
    image: postgres:16
    hostname: postgres
    environment:
      POSTGRES_DB: db_shop_test
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: 310198iko
    ports:
      - "5445:5432"
    restart: always


volumes:
  postgres_data: